### ISSUE TITLE
windows and linux java classpath separator

### ISSUE THREAD

**Issue by windqyoung** [dsiddharth2/php-zxing#1]
https://github.com/dsiddharth2/php-zxing/blob/bbc0cd2cc4207d7973f392365eadce8397234595/src/PHPZxing/PHPZxingDecoder.php#L88

the separator in windows and linux is not same, Can you add a judgment

$sep = DIRECTORY_SEPARATOR === '/' ? ':' : ';';

**Comment by dsiddharth2** [comment]
We have PATH_SEPARATOR for that, so I am adding that now.

**Comment by dsiddharth2** [comment]
Added PATH_SEPARATOR :)

**Comment by windqyoung** [comment]
好, 我忘了有这个 PATH_SEPARATOR  常量 了.

Good, thanks.
