### ISSUE TITLE
Error Interface

### ISSUE THREAD

**Issue by joaofalcao67** [dsiddharth2/php-zxing#12]
I have this error can you please help me
PHP Fatal error:  Interface 'PHPZxing\PHPZxingInterface' not found in C:\inetpub\wwwroot\saude\dw\PHPZxing\ZxingBarNotFound.php on line 41

line 41   class ZxingBarNotFound implements PHPZxingInterface i got same error on all phppages 

another  at example.php

PHP Fatal error:  Uncaught Error: Call to a member function isFound() on null in C:\inetpub\wwwroot\saude\dw\examples\example.php:50
Stack trace:
#0 {main}
  thrown in C:\inetpub\wwwroot\saude\dw\examples\example.php on line 50

Can you please help me

best regards

Thank you

**Comment by sid-mildlyclassic** [comment]
Hi I will try to do this on my windows machine and get back to you. @joaofalcao67

**Comment by dsiddharth2** [comment]
Hi @joaofalcao67 I am going to try this in my windows machine and check and get back to you.

**Comment by dsiddharth2** [comment]
Hi @joaofalcao67 Did you include the class?

So if you are running directly, you have got to require the files.

Example,

`require PHPZxingBase.php`

for every file.

My suggestion is to use composer to do same.

Does this help you ?

**Comment by dsiddharth2** [comment]
Hi,

Did you try doing this?

I am closing the problem for now, if it does not work please open the issue again
