### ISSUE TITLE
decoder warning

### ISSUE THREAD

**Issue by yoshikawa** [dsiddharth2/php-zxing#2]
Im sorry if there are mistakes.

PHPZxingDecoder.php, line 186
[Counting of non-countable objects](https://wiki.php.net/rfc/counting_non_countables)
In PHP7.2, calling count() with a parameter that is a scalar, null, or an object that doesn't implement Countable.
Do you have any plans to solve this problem?

**Comment by dsiddharth2** [comment]
Yes I will solve this problem. Give me some time. This plugin was programmed on PHP 5.6 or something. I have to test on 7+

**Comment by yoshikawa** [comment]
Thank U! :)
ありがとうございます！

**Comment by dsiddharth2** [comment]
Hello YoshikawaTaiki,
I have fixed the issue, by removing the count scalar condition. Please can you update and check if it displays the same problem ?

**Comment by yoshikawa** [comment]
It's working as expected!Thank U!
