### ISSUE TITLE
Cannot detect if it was successful or not

### ISSUE THREAD

**Issue by Enormity** [dsiddharth2/php-zxing#3]
The functions for determining if there was an error do not work if there was not an error, and you get a fatal error for calling "getErrorMessage/getErrorCode".  These should work either way and just not return anything.

Likewise, you cannot call the successful messages if there was an error.  So I cannot check to see if no bar code was returned to know to show the error either.

**Comment by dsiddharth2** [comment]
Hi,
Okay, I will check the code and get back to you on this. Also I will write some examples that will describe how to check if there is an error or a success. Let us see if that solves your problem.

**Comment by dsiddharth2** [comment]
Hi,
I updated the code now, added isFound Function. Please check now.

Let me know if it solves your problem. For now I am closing this issue, please reopen if the problem persists.
